INSERT INTO suddivisione VALUES ('AvambracciA1',8888,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB2',8879,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C3',8870,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD4',8861,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA2',8852,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB3',8843,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC4',8834,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D5',8825,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A3',8816,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B4',8807,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC5',8798,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD6',8789,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA4',8780,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B5',8771,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA2',8762,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB3',8888,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C4',8879,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD5',8870,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA3',8861,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB4',8852,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC5',8843,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D6',8834,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A4',8825,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B5',8816,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC6',8807,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD7',8798,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA5',8789,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B6',8780,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA2',8771,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB3',8627,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C4',8888,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD5',8879,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA3',8870,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB4',8861,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC5',8852,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D6',8843,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A4',8834,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B5',8825,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC6',8816,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD7',8807,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA5',8798,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B6',8789,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA3',8780,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB4',8771,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C5',8492,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD6',8888,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA4',8879,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB5',8870,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC6',8861,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D7',8852,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A5',8843,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B6',8834,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC7',8825,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD8',8816,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA6',8807,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B7',8798,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA3',8789,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB4',8780,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C5',8771,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD6',8357,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA4',8888,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB5',8879,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC6',8870,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D7',8861,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A5',8852,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B6',8843,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC7',8834,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD8',8825,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA6',8816,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B7',8807,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA4',8798,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB5',8789,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C6',8780,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD7',8771,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA5',8222,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB6',8213,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC7',8204,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D8',8195,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A6',8186,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B7',8177,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC8',8168,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD9',8159,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA7',8222,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B8',8213,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA4',8204,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB5',8195,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C6',8186,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD7',8177,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA5',8168,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB6',8159,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC7',8222,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D8',8213,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A6',8204,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B7',8195,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC8',8186,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD9',8177,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA7',8168,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B8',8159,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA5',8006,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB6',7997,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C7',7988,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD8',7979,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA6',7970,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB7',7961,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC8',7952,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D9',7943,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A7',7934,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B8',7925,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC9',7916,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD10',7907,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA8',7898,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B9',7889,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA5',7880,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB6',7871,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C7',7862,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD8',7853,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA6',7844,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB7',7835,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC8',7826,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D9',7817,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A7',7808,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B8',7799,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC9',7790,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD10',7781,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA8',7772,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B9',7763,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA6',7754,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB7',7745,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C8',7736,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD9',7727,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA7',7718,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB8',7709,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC9',7817,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D10',7808,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A8',7799,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B9',7790,'mercoledì');
INSERT INTO suddivisione VALUES ('FianchiC10',7781,'giovedì');
INSERT INTO suddivisione VALUES ('LombariD11',7772,'venerdì');
INSERT INTO suddivisione VALUES ('PettoraliA9',7763,'sabato');
INSERT INTO suddivisione VALUES ('Trapezi B10',7754,'domenica');
INSERT INTO suddivisione VALUES ('AvambracciA6',7745,'lunedì');
INSERT INTO suddivisione VALUES ('BicipitiB7',7736,'martedì');
INSERT INTO suddivisione VALUES ('Deltoidi C8',7727,'mercoledì');
INSERT INTO suddivisione VALUES ('TricipitiD9',7718,'giovedì');
INSERT INTO suddivisione VALUES ('Bicipiti FemoraliA7',7709,'venerdì');
INSERT INTO suddivisione VALUES ('GluteiB8',7583,'sabato');
INSERT INTO suddivisione VALUES ('PolpacciC9',7574,'domenica');
INSERT INTO suddivisione VALUES ('Quadricipiti D10',7565,'lunedì');
INSERT INTO suddivisione VALUES ('Addominali A8',7556,'martedì');
INSERT INTO suddivisione VALUES ('Dorsali B9',7547,'mercoledì');
