INSERT INTO allenamento VALUES (102,'AvambracciA1');
INSERT INTO allenamento VALUES (104,'BicipitiB1');
INSERT INTO allenamento VALUES (105,'Deltoidi C1');
INSERT INTO allenamento VALUES (107,'Bicipiti FemoraliC3');
INSERT INTO allenamento VALUES (108,'GluteiD3');
INSERT INTO allenamento VALUES (110,'PolpacciA4');
INSERT INTO allenamento VALUES (111,'Quadricipiti B4');
INSERT INTO allenamento VALUES (113,'Quadricipiti D2');
INSERT INTO allenamento VALUES (114,'Addominali A2');
INSERT INTO allenamento VALUES (116,'Dorsali B2');
INSERT INTO allenamento VALUES (117,'FianchiC2');
INSERT INTO allenamento VALUES (119,'LombariD2');
INSERT INTO allenamento VALUES (120,'PettoraliA3');
INSERT INTO allenamento VALUES (122,'Trapezi B3');
INSERT INTO allenamento VALUES (123,'AvambracciC3');
INSERT INTO allenamento VALUES (125,'BicipitiD3');
INSERT INTO allenamento VALUES (126,'Deltoidi A3');
INSERT INTO allenamento VALUES (128,'TricipitiB3');
INSERT INTO allenamento VALUES (129,'Bicipiti FemoraliC3');
INSERT INTO allenamento VALUES (131,'GluteiD3');
INSERT INTO allenamento VALUES (132,'PolpacciA4');
INSERT INTO allenamento VALUES (134,'Quadricipiti B4');
INSERT INTO allenamento VALUES (135,'Addominali C4');
INSERT INTO allenamento VALUES (137,'Dorsali D4');
INSERT INTO allenamento VALUES (138,'FianchiA4');
INSERT INTO allenamento VALUES (140,'LombariB4');
INSERT INTO allenamento VALUES (141,'PettoraliC4');
INSERT INTO allenamento VALUES (143,'Trapezi D4');
INSERT INTO allenamento VALUES (144,'AvambracciA5');
INSERT INTO allenamento VALUES (146,'BicipitiB5');
INSERT INTO allenamento VALUES (147,'Deltoidi C5');
INSERT INTO allenamento VALUES (149,'TricipitiD5');
INSERT INTO allenamento VALUES (150,'Bicipiti FemoraliA5');
INSERT INTO allenamento VALUES (152,'GluteiB5');
INSERT INTO allenamento VALUES (153,'PolpacciC5');
INSERT INTO allenamento VALUES (155,'Quadricipiti D5');
INSERT INTO allenamento VALUES (156,'AvambracciA1');
INSERT INTO allenamento VALUES (158,'BicipitiB1');
INSERT INTO allenamento VALUES (159,'Deltoidi C1');
INSERT INTO allenamento VALUES (161,'TricipitiD1');
INSERT INTO allenamento VALUES (162,'Bicipiti FemoraliA2');
INSERT INTO allenamento VALUES (164,'GluteiB2');
INSERT INTO allenamento VALUES (165,'PolpacciC2');
INSERT INTO allenamento VALUES (167,'Bicipiti FemoraliC3');
INSERT INTO allenamento VALUES (168,'GluteiD3');
INSERT INTO allenamento VALUES (170,'PolpacciA4');
INSERT INTO allenamento VALUES (171,'Quadricipiti B4');
INSERT INTO allenamento VALUES (173,'GluteiD7');
INSERT INTO allenamento VALUES (174,'PolpacciA7');
INSERT INTO allenamento VALUES (176,'Quadricipiti B7');
INSERT INTO allenamento VALUES (177,'Addominali C7');
INSERT INTO allenamento VALUES (179,'Dorsali D7');
INSERT INTO allenamento VALUES (180,'PolpacciC2');
INSERT INTO allenamento VALUES (182,'Quadricipiti D2');
INSERT INTO allenamento VALUES (183,'Addominali A2');
INSERT INTO allenamento VALUES (185,'Trapezi D8');
INSERT INTO allenamento VALUES (186,'AvambracciA8');
INSERT INTO allenamento VALUES (188,'BicipitiB8');
INSERT INTO allenamento VALUES (189,'Deltoidi C8');
INSERT INTO allenamento VALUES (191,'TricipitiD8');
INSERT INTO allenamento VALUES (192,'Bicipiti FemoraliA9');
INSERT INTO allenamento VALUES (194,'GluteiB9');
INSERT INTO allenamento VALUES (195,'PolpacciC9');
INSERT INTO allenamento VALUES (197,'Quadricipiti D9');
INSERT INTO allenamento VALUES (198,'Addominali A9');
INSERT INTO allenamento VALUES (200,'Dorsali B9');
INSERT INTO allenamento VALUES (201,'FianchiC9');
INSERT INTO allenamento VALUES (203,'LombariD9');
INSERT INTO allenamento VALUES (204,'PettoraliA10');
INSERT INTO allenamento VALUES (206,'AvambracciA1');
INSERT INTO allenamento VALUES (207,'BicipitiB1');
INSERT INTO allenamento VALUES (209,'Deltoidi C1');
INSERT INTO allenamento VALUES (210,'TricipitiD1');
INSERT INTO allenamento VALUES (212,'Bicipiti FemoraliA2');
INSERT INTO allenamento VALUES (213,'GluteiB2');
INSERT INTO allenamento VALUES (215,'PolpacciC2');
INSERT INTO allenamento VALUES (216,'Quadricipiti D2');
INSERT INTO allenamento VALUES (218,'Addominali A2');
INSERT INTO allenamento VALUES (219,'Dorsali B2');
INSERT INTO allenamento VALUES (221,'Dorsali D11');
INSERT INTO allenamento VALUES (222,'FianchiA11');
INSERT INTO allenamento VALUES (224,'LombariB11');
INSERT INTO allenamento VALUES (225,'PettoraliC11');
INSERT INTO allenamento VALUES (227,'Trapezi D11');
INSERT INTO allenamento VALUES (228,'AvambracciA12');
INSERT INTO allenamento VALUES (230,'BicipitiB12');
INSERT INTO allenamento VALUES (231,'Deltoidi C12');
INSERT INTO allenamento VALUES (233,'TricipitiD12');
INSERT INTO allenamento VALUES (234,'Bicipiti FemoraliA12');
INSERT INTO allenamento VALUES (236,'GluteiB12');
INSERT INTO allenamento VALUES (237,'PolpacciC12');
INSERT INTO allenamento VALUES (239,'Quadricipiti D12');
INSERT INTO allenamento VALUES (240,'Addominali A13');
INSERT INTO allenamento VALUES (242,'Dorsali B13');
INSERT INTO allenamento VALUES (243,'FianchiC13');
INSERT INTO allenamento VALUES (245,'LombariD13');
INSERT INTO allenamento VALUES (246,'PettoraliA13');
INSERT INTO allenamento VALUES (248,'Trapezi B13');
INSERT INTO allenamento VALUES (179,'AvambracciC13');
INSERT INTO allenamento VALUES (102,'BicipitiD13');
INSERT INTO allenamento VALUES (104,'Deltoidi A14');
INSERT INTO allenamento VALUES (105,'TricipitiB14');
INSERT INTO allenamento VALUES (107,'PettoraliA13');
INSERT INTO allenamento VALUES (108,'Trapezi B13');
INSERT INTO allenamento VALUES (110,'PolpacciA14');
INSERT INTO allenamento VALUES (111,'Quadricipiti B14');
INSERT INTO allenamento VALUES (113,'AvambracciC14');
INSERT INTO allenamento VALUES (114,'BicipitiD14');
INSERT INTO allenamento VALUES (116,'Deltoidi A15');
INSERT INTO allenamento VALUES (117,'TricipitiB15');
INSERT INTO allenamento VALUES (119,'Bicipiti FemoraliC15');
INSERT INTO allenamento VALUES (120,'GluteiD15');
INSERT INTO allenamento VALUES (122,'PolpacciA15');
INSERT INTO allenamento VALUES (123,'Quadricipiti B15');
INSERT INTO allenamento VALUES (125,'AvambracciC15');
INSERT INTO allenamento VALUES (126,'BicipitiD15');
INSERT INTO allenamento VALUES (128,'Deltoidi A16');
INSERT INTO allenamento VALUES (129,'TricipitiB16');
INSERT INTO allenamento VALUES (131,'Bicipiti FemoraliC16');
INSERT INTO allenamento VALUES (132,'Quadricipiti B14');
INSERT INTO allenamento VALUES (134,'AvambracciC14');
INSERT INTO allenamento VALUES (135,'BicipitiD14');
INSERT INTO allenamento VALUES (137,'AvambracciC16');
INSERT INTO allenamento VALUES (138,'AvambracciA1');
INSERT INTO allenamento VALUES (140,'BicipitiB1');
INSERT INTO allenamento VALUES (141,'Deltoidi C1');
INSERT INTO allenamento VALUES (143,'TricipitiD1');
INSERT INTO allenamento VALUES (144,'Bicipiti FemoraliA2');
INSERT INTO allenamento VALUES (146,'GluteiB2');
INSERT INTO allenamento VALUES (147,'PolpacciC2');
INSERT INTO allenamento VALUES (149,'Quadricipiti D2');
INSERT INTO allenamento VALUES (150,'Addominali A2');
INSERT INTO allenamento VALUES (152,'Dorsali B2');
INSERT INTO allenamento VALUES (153,'TricipitiB18');
INSERT INTO allenamento VALUES (155,'Bicipiti FemoraliC18');
INSERT INTO allenamento VALUES (156,'GluteiD18');
INSERT INTO allenamento VALUES (158,'PolpacciA18');
INSERT INTO allenamento VALUES (159,'Quadricipiti B18');
INSERT INTO allenamento VALUES (161,'AvambracciC18');
INSERT INTO allenamento VALUES (162,'BicipitiD18');
INSERT INTO allenamento VALUES (164,'Deltoidi A19');
INSERT INTO allenamento VALUES (165,'AvambracciA1');
INSERT INTO allenamento VALUES (167,'BicipitiB1');
INSERT INTO allenamento VALUES (168,'Deltoidi C1');
INSERT INTO allenamento VALUES (170,'TricipitiD1');
INSERT INTO allenamento VALUES (171,'Bicipiti FemoraliA2');
INSERT INTO allenamento VALUES (173,'GluteiB2');
INSERT INTO allenamento VALUES (174,'PolpacciC2');
INSERT INTO allenamento VALUES (176,'Quadricipiti D2');
INSERT INTO allenamento VALUES (177,'Addominali A2');
