INSERT INTO potenziamento_muscolare VALUES ('Potenziamento1','Avambracci','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento2','Bicipiti','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento3','Deltoidi','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento4','Tricipiti ','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento5','Bicipiti Femorali ','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento6','Glutei ','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento7','Polpacci ','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento8','Quadricipiti ','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento9','Addominali ','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento10','Dorsali ','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento11','Fianchi','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento12','Lombari','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento13','Pettorali','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento14','Trapezi ','minimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento15','Avambracci','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento16','Bicipiti','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento17','Deltoidi','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento18','Tricipiti ','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento19','Bicipiti Femorali ','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento20','Glutei ','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento21','Polpacci ','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento22','Quadricipiti ','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento23','Addominali ','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento24','Dorsali ','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento25','Fianchi','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento26','Lombari','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento27','Pettorali','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento28','Trapezi ','lieve');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento29','Avambracci','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento30','Bicipiti','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento31','Deltoidi','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento32','Tricipiti ','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento33','Bicipiti Femorali ','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento34','Glutei ','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento35','Polpacci ','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento36','Quadricipiti ','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento37','Addominali ','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento38','Dorsali ','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento39','Fianchi','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento40','Lombari','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento41','Pettorali','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento42','Trapezi ','moderato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento43','Avambracci','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento44','Bicipiti','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento45','Deltoidi','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento46','Tricipiti ','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento47','Bicipiti Femorali ','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento48','Glutei ','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento49','Polpacci ','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento50','Quadricipiti ','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento51','Addominali ','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento52','Dorsali ','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento53','Fianchi','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento54','Lombari','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento55','Pettorali','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento56','Trapezi ','elevato');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento57','Avambracci','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento58','Bicipiti','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento59','Deltoidi','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento60','Tricipiti ','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento61','Bicipiti Femorali ','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento62','Glutei ','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento63','Polpacci ','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento64','Quadricipiti ','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento65','Addominali ','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento66','Dorsali ','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento67','Fianchi','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento68','Lombari','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento69','Pettorali','massimo');
INSERT INTO potenziamento_muscolare VALUES ('Potenziamento70','Trapezi ','massimo');
