INSERT INTO pagamento_rateizzato VALUES (6384,'Banca Monte dei Paschi di Siena SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6390,'Intesa Sanpaolo SpA',4);
INSERT INTO pagamento_rateizzato VALUES (6396,'Banco Popolare - Società Cooperativa',3);
INSERT INTO pagamento_rateizzato VALUES (6402,'Banca Nazionale del Lavoro Spa',3);
INSERT INTO pagamento_rateizzato VALUES (6408,'Banca Popolare di Milano Scarl',6);
INSERT INTO pagamento_rateizzato VALUES (6414,'Banco di Napoli SpA',7);
INSERT INTO pagamento_rateizzato VALUES (6420,'Cassa di Risparmio di Parma e Piacenza SpA',4);
INSERT INTO pagamento_rateizzato VALUES (6426,'Banca Popolare di Vicenza SCpA',3);
INSERT INTO pagamento_rateizzato VALUES (6432,'Banca Popolare Dell Emilia Romagna - Società Cooperativa',2);
INSERT INTO pagamento_rateizzato VALUES (6438,'Credito Emiliano SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6444,'Banco di Sardegna SpA',4);
INSERT INTO pagamento_rateizzato VALUES (6450,'Veneto Banca S.C.P.A.',3);
INSERT INTO pagamento_rateizzato VALUES (6456,'Cassa di Risparmio del Veneto SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6462,'Banca Piccolo Credito Valtellinese, Società Cooperativa',6);
INSERT INTO pagamento_rateizzato VALUES (6468,'Banca Popolare di Bergamo SpA',7);
INSERT INTO pagamento_rateizzato VALUES (6474,'Banca Carige Italia Spa',4);
INSERT INTO pagamento_rateizzato VALUES (6480,'Deutsche Bank SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6486,'Banco di Brescia San Paolo Cab SpA',2);
INSERT INTO pagamento_rateizzato VALUES (6492,'Banca Popolare di Sondrio SCpA',3);
INSERT INTO pagamento_rateizzato VALUES (6498,'Banca delle Marche SpA',4);
INSERT INTO pagamento_rateizzato VALUES (6504,'Banca Sella SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6510,'Unipol Banca Spa',3);
INSERT INTO pagamento_rateizzato VALUES (6516,'Cassa di Risparmio di Firenze SpA',6);
INSERT INTO pagamento_rateizzato VALUES (6522,'Banca Carime SpA',7);
INSERT INTO pagamento_rateizzato VALUES (6528,'Banca Regionale Europea SpA',4);
INSERT INTO pagamento_rateizzato VALUES (6534,'Credito Bergamasco SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6540,'Banca Popolare Commercio e Industria SpA',2);
INSERT INTO pagamento_rateizzato VALUES (6546,'Banca Popolare di Ancona SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6552,'Banca dell Adriatico SpA',4);
INSERT INTO pagamento_rateizzato VALUES (6558,'Banca Carige SpA - Cassa di Risparmio di Genova e Imperia',3);
INSERT INTO pagamento_rateizzato VALUES (6564,'Banca Popolare Friuladria SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6570,'Banca Popolare di Bari SCpA',6);
INSERT INTO pagamento_rateizzato VALUES (6576,'Cassa di Risparmio in Bologna SpA',7);
INSERT INTO pagamento_rateizzato VALUES (6582,'Banca Popolare dell Etruria e del Lazio - Società Cooperativa',4);
INSERT INTO pagamento_rateizzato VALUES (6588,'Banco di Desio e Della Brianza SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6594,'Banca Popolare di Puglia e Basilicata SCpA',2);
INSERT INTO pagamento_rateizzato VALUES (6600,'Banca di Credito Cooperativo di Roma Società Cooperativa',3);
INSERT INTO pagamento_rateizzato VALUES (6606,'Cassa di Risparmio di Bolzano SpA - Südtiroler Sparkasse Ag',4);
INSERT INTO pagamento_rateizzato VALUES (6612,'Intesa Sanpaolo Private Banking SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6618,'Banca Monte dei Paschi di Siena SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6624,'Intesa Sanpaolo SpA',6);
INSERT INTO pagamento_rateizzato VALUES (6630,'Banco Popolare - Società Cooperativa',7);
INSERT INTO pagamento_rateizzato VALUES (6636,'Banca Nazionale del Lavoro Spa',4);
INSERT INTO pagamento_rateizzato VALUES (6642,'Banca Popolare di Milano Scarl',3);
INSERT INTO pagamento_rateizzato VALUES (6648,'Banco di Napoli SpA',2);
INSERT INTO pagamento_rateizzato VALUES (6654,'Cassa di Risparmio di Parma e Piacenza SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6660,'Banca Popolare di Vicenza SCpA',4);
INSERT INTO pagamento_rateizzato VALUES (6666,'Banca Popolare Dell Emilia Romagna - Società Cooperativa',3);
INSERT INTO pagamento_rateizzato VALUES (6672,'Credito Emiliano SpA',3);
INSERT INTO pagamento_rateizzato VALUES (6678,'Banco di Sardegna SpA',6);
