INSERT INTO attrezzatura VALUES (102,'panca 45°','Vogatore');
INSERT INTO attrezzatura VALUES (104,'peso 15 kg','Tapis Roulant ');
INSERT INTO attrezzatura VALUES (105,'peso 14 kg','Shoulder Press');
INSERT INTO attrezzatura VALUES (107,'peso 12 kg','Pulley');
INSERT INTO attrezzatura VALUES (108,'panca 30°','Pressa');
INSERT INTO attrezzatura VALUES (110,'peso 20 kg','Pectoral Machine');
INSERT INTO attrezzatura VALUES (111,'bilanciere 5 kg','Panca Per Addominali');
INSERT INTO attrezzatura VALUES (113,'velocità 8','Panca');
INSERT INTO attrezzatura VALUES (114,'resistenza 5','Manubri E Bilanciere');
INSERT INTO attrezzatura VALUES (116,'resistenza 6','Leg Extension');
INSERT INTO attrezzatura VALUES (117,'resistenza 7','Leg Curl');
INSERT INTO attrezzatura VALUES (119,'resistenza 8','Lat Machine');
INSERT INTO attrezzatura VALUES (120,'resistenza 9','Hyperextension');
INSERT INTO attrezzatura VALUES (122,'resistenza 10','Hack Squat');
INSERT INTO attrezzatura VALUES (123,'resistenza 11','Gluteus Machine');
INSERT INTO attrezzatura VALUES (125,'resistenza 12','Ellittica');
INSERT INTO attrezzatura VALUES (126,'resistenza 13','Cyclette Reclinata');
INSERT INTO attrezzatura VALUES (128,'resistenza 14','Cyclette');
INSERT INTO attrezzatura VALUES (129,'velocità 8','Chest Press');
INSERT INTO attrezzatura VALUES (131,'velocità 7','Cavi');
INSERT INTO attrezzatura VALUES (132,'velocità 6','Calf Machine');
INSERT INTO attrezzatura VALUES (134,'velocità 5','Barra Trazioni');
INSERT INTO attrezzatura VALUES (135,'velocità 4','Attrezzi Polifunzionali');
INSERT INTO attrezzatura VALUES (137,'velocità 3','Attrezzi ');
INSERT INTO attrezzatura VALUES (138,'velocità 2','Attrezzi ');
INSERT INTO attrezzatura VALUES (140,'velocità 1','Attrezzi Per Addominali E Cardio');
INSERT INTO attrezzatura VALUES (141,'velocità 0','Adductor Machine');
INSERT INTO attrezzatura VALUES (143,'velocità 1','Abductor Machine');
INSERT INTO attrezzatura VALUES (144,'velocità 2','Vogatore');
INSERT INTO attrezzatura VALUES (146,'velocità 3','Tapis Roulant ');
INSERT INTO attrezzatura VALUES (147,'velocità 4','Shoulder Press');
INSERT INTO attrezzatura VALUES (149,'panca 90°','Pulley');
INSERT INTO attrezzatura VALUES (150,'panca 60°','Pressa');
INSERT INTO attrezzatura VALUES (152,'panca piana','Pectoral Machine');
INSERT INTO attrezzatura VALUES (153,'panca piana e bilaciere 5 kg','Panca Per Addominali');
INSERT INTO attrezzatura VALUES (155,'panca 45° peso 8 kg','Panca');
INSERT INTO attrezzatura VALUES (156,'panca piana','Manubri E Bilanciere');
INSERT INTO attrezzatura VALUES (158,'panca 90° peso 11kg','Leg Extension');
INSERT INTO attrezzatura VALUES (159,'panca 45°','Leg Curl');
INSERT INTO attrezzatura VALUES (161,'peso 15 kg','Lat Machine');
INSERT INTO attrezzatura VALUES (162,'peso 14 kg','Hyperextension');
INSERT INTO attrezzatura VALUES (164,'peso 12 kg','Hack Squat');
INSERT INTO attrezzatura VALUES (165,'panca 30°','Gluteus Machine');
INSERT INTO attrezzatura VALUES (167,'peso 20 kg','Ellittica');
INSERT INTO attrezzatura VALUES (168,'bilanciere 5 kg','Cyclette Reclinata');
INSERT INTO attrezzatura VALUES (170,'velocità 9','Cyclette');
INSERT INTO attrezzatura VALUES (171,'resistenza 15','Chest Press');
INSERT INTO attrezzatura VALUES (173,'resistenza 16','Cavi');
INSERT INTO attrezzatura VALUES (174,'resistenza 17','Calf Machine');
INSERT INTO attrezzatura VALUES (176,'resistenza 18','Barra Trazioni');
INSERT INTO attrezzatura VALUES (177,'resistenza 19','Attrezzi Polifunzionali');
INSERT INTO attrezzatura VALUES (179,'resistenza 20','Attrezzi Per ');
INSERT INTO attrezzatura VALUES (180,'resistenza 21','Attrezzi Per');
INSERT INTO attrezzatura VALUES (182,'resistenza 22','Attrezzi Per Addominali E Cardio');
INSERT INTO attrezzatura VALUES (183,'resistenza 23','Adductor Machine');
INSERT INTO attrezzatura VALUES (185,'resistenza 24','Abductor Machine');
INSERT INTO attrezzatura VALUES (186,'velocità 5','Vogatore');
INSERT INTO attrezzatura VALUES (188,'velocità 6','Tapis Roulant ');
INSERT INTO attrezzatura VALUES (189,'velocità 7','Shoulder Press');
INSERT INTO attrezzatura VALUES (191,'velocità 8','Pulley');
INSERT INTO attrezzatura VALUES (192,'velocità 9','Pressa');
INSERT INTO attrezzatura VALUES (194,'velocità 10','Pectoral Machine');
INSERT INTO attrezzatura VALUES (195,'velocità 11','Panca Per Addominali');
INSERT INTO attrezzatura VALUES (197,'velocità 12','Panca');
INSERT INTO attrezzatura VALUES (198,'velocità 13','Manubri E Bilanciere');
INSERT INTO attrezzatura VALUES (200,'velocità 14','Leg Extension');
INSERT INTO attrezzatura VALUES (201,'velocità 15','Leg Curl');
INSERT INTO attrezzatura VALUES (203,'velocità 16','Lat Machine');
INSERT INTO attrezzatura VALUES (204,'velocità 17','Hyperextension');
INSERT INTO attrezzatura VALUES (206,'panca 90°','Hack Squat');
INSERT INTO attrezzatura VALUES (207,'panca 60°','Gluteus Machine');
INSERT INTO attrezzatura VALUES (209,'panca piana','Ellittica');
INSERT INTO attrezzatura VALUES (210,'panca piana e bilaciere 5 kg','Cyclette Reclinata');
INSERT INTO attrezzatura VALUES (212,'panca 45° peso 8 kg','Cyclette');
INSERT INTO attrezzatura VALUES (213,'panca piana','Chest Press');
INSERT INTO attrezzatura VALUES (215,'panca 90° peso 11kg','Cavi');
INSERT INTO attrezzatura VALUES (216,'panca 45°','Calf Machine');
INSERT INTO attrezzatura VALUES (218,'peso 15 kg','Barra Trazioni');
INSERT INTO attrezzatura VALUES (219,'peso 14 kg','Attrezzi Polifunzionali');
INSERT INTO attrezzatura VALUES (221,'peso 12 kg','Attrezzi Per ');
INSERT INTO attrezzatura VALUES (222,'panca 30°','Attrezzi Per ');
INSERT INTO attrezzatura VALUES (224,'peso 20 kg','Attrezzi Per Addominali E Cardio');
INSERT INTO attrezzatura VALUES (225,'bilanciere 5 kg','Adductor Machine');
INSERT INTO attrezzatura VALUES (227,'velocità 10','Abductor Machine');
INSERT INTO attrezzatura VALUES (228,'resistenza 25','Vogatore');
INSERT INTO attrezzatura VALUES (230,'resistenza 26','Tapis Roulant ');
INSERT INTO attrezzatura VALUES (231,'resistenza 27','Shoulder Press');
INSERT INTO attrezzatura VALUES (233,'resistenza 28','Pulley');
INSERT INTO attrezzatura VALUES (234,'resistenza 29','Pressa');
INSERT INTO attrezzatura VALUES (236,'resistenza 30','Pectoral Machine');
INSERT INTO attrezzatura VALUES (237,'resistenza 31','Panca Per Addominali');
INSERT INTO attrezzatura VALUES (239,'resistenza 32','Panca');
INSERT INTO attrezzatura VALUES (240,'resistenza 33','Manubri E Bilanciere');
INSERT INTO attrezzatura VALUES (242,'resistenza 34','Leg Extension');
INSERT INTO attrezzatura VALUES (243,'velocità 18','Leg Curl');
INSERT INTO attrezzatura VALUES (245,'velocità 19','Lat Machine');
INSERT INTO attrezzatura VALUES (246,'velocità 20','Hyperextension');
INSERT INTO attrezzatura VALUES (248,'velocità 21','Hack Squat');
INSERT INTO attrezzatura VALUES (102,'velocità 22','Gluteus Machine');
INSERT INTO attrezzatura VALUES (104,'velocità 23','Ellittica');
INSERT INTO attrezzatura VALUES (105,'velocità 24','Cyclette Reclinata');
INSERT INTO attrezzatura VALUES (107,'velocità 25','Cyclette');
INSERT INTO attrezzatura VALUES (108,'velocità 26','Chest Press');
INSERT INTO attrezzatura VALUES (110,'velocità 27','Cavi');
INSERT INTO attrezzatura VALUES (111,'velocità 28','Calf Machine');
INSERT INTO attrezzatura VALUES (113,'velocità 29','Barra Trazioni');
INSERT INTO attrezzatura VALUES (114,'velocità 30','Attrezzi Polifunzionali');
INSERT INTO attrezzatura VALUES (116,'panca 90°','Attrezzi Pe');
INSERT INTO attrezzatura VALUES (117,'panca 60°','Attrezzi ');
INSERT INTO attrezzatura VALUES (119,'panca piana','Attrezzi Per Addominali E Cardio');
INSERT INTO attrezzatura VALUES (120,'panca piana e bilaciere 5 kg','Adductor Machine');
INSERT INTO attrezzatura VALUES (122,'panca 45° peso 8 kg','Abductor Machine');
INSERT INTO attrezzatura VALUES (123,'panca piana','Vogatore');
INSERT INTO attrezzatura VALUES (125,'panca 90° peso 11kg','Tapis Roulant ');
INSERT INTO attrezzatura VALUES (126,'panca 45°','Shoulder Press');
INSERT INTO attrezzatura VALUES (128,'peso 15 kg','Pulley');
INSERT INTO attrezzatura VALUES (129,'peso 14 kg','Pressa');
INSERT INTO attrezzatura VALUES (131,'peso 12 kg','Pectoral Machine');
INSERT INTO attrezzatura VALUES (132,'panca 30°','Panca Per Addominali');
INSERT INTO attrezzatura VALUES (134,'peso 20 kg','Panca');
INSERT INTO attrezzatura VALUES (135,'bilanciere 5 kg','Manubri E Bilanciere');
INSERT INTO attrezzatura VALUES (137,'velocità 11','Leg Extension');
INSERT INTO attrezzatura VALUES (138,'resistenza 35','Vogatore');
INSERT INTO attrezzatura VALUES (140,'resistenza 36','Tapis Roulant ');
INSERT INTO attrezzatura VALUES (141,'resistenza 37','Shoulder Press');
INSERT INTO attrezzatura VALUES (143,'resistenza 38','Pulley');
INSERT INTO attrezzatura VALUES (144,'resistenza 39','Pressa');
INSERT INTO attrezzatura VALUES (146,'resistenza 40','Pectoral Machine');
INSERT INTO attrezzatura VALUES (147,'resistenza 41','Panca Per Addominali');
INSERT INTO attrezzatura VALUES (149,'resistenza 42','Panca');
INSERT INTO attrezzatura VALUES (150,'resistenza 43','Manubri E Bilanciere');
INSERT INTO attrezzatura VALUES (152,'resistenza 44','Leg Extension');
INSERT INTO attrezzatura VALUES (153,'velocità 31','Leg Curl');
INSERT INTO attrezzatura VALUES (155,'velocità 32','Lat Machine');
INSERT INTO attrezzatura VALUES (156,'velocità 33','Hyperextension');
INSERT INTO attrezzatura VALUES (158,'velocità 34','Hack Squat');
INSERT INTO attrezzatura VALUES (159,'velocità 35','Gluteus Machine');
INSERT INTO attrezzatura VALUES (161,'velocità 36','Ellittica');
INSERT INTO attrezzatura VALUES (162,'velocità 37','Cyclette Reclinata');
INSERT INTO attrezzatura VALUES (164,'velocità 38','Cyclette');
INSERT INTO attrezzatura VALUES (165,'velocità 39','Chest Press');
INSERT INTO attrezzatura VALUES (167,'velocità 40','Cavi');
INSERT INTO attrezzatura VALUES (168,'velocità 41','Calf Machine');
INSERT INTO attrezzatura VALUES (170,'velocità 42','Barra Trazioni');
INSERT INTO attrezzatura VALUES (171,'velocità 43','Attrezzi Polifunzionali');
INSERT INTO attrezzatura VALUES (173,'panca 90°','Attrezzi ');
INSERT INTO attrezzatura VALUES (174,'panca 60°','Attrezzi');
INSERT INTO attrezzatura VALUES (176,'panca piana','Attrezzi Per Addominali E Cardio');
INSERT INTO attrezzatura VALUES (177,'panca piana e bilaciere 5 kg','Adductor Machine');
INSERT INTO attrezzatura VALUES (179,'panca 45° peso 8 kg','Abductor Machine');
