INSERT INTO sessione VALUES ('AvambracciA1');
INSERT INTO sessione VALUES ('BicipitiB1');
INSERT INTO sessione VALUES ('Deltoidi C1');
INSERT INTO sessione VALUES ('TricipitiD1');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA2');
INSERT INTO sessione VALUES ('GluteiB2');
INSERT INTO sessione VALUES ('PolpacciC2');
INSERT INTO sessione VALUES ('Quadricipiti D2');
INSERT INTO sessione VALUES ('AvambracciA2');
INSERT INTO sessione VALUES ('BicipitiB2');
INSERT INTO sessione VALUES ('Deltoidi C2');
INSERT INTO sessione VALUES ('TricipitiD2');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA3');
INSERT INTO sessione VALUES ('GluteiB3');
INSERT INTO sessione VALUES ('PolpacciC3');
INSERT INTO sessione VALUES ('Quadricipiti D3');
INSERT INTO sessione VALUES ('AvambracciA3');
INSERT INTO sessione VALUES ('BicipitiB3');
INSERT INTO sessione VALUES ('Deltoidi C3');
INSERT INTO sessione VALUES ('TricipitiD3');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA4');
INSERT INTO sessione VALUES ('GluteiB4');
INSERT INTO sessione VALUES ('PolpacciC4');
INSERT INTO sessione VALUES ('Quadricipiti D4');
INSERT INTO sessione VALUES ('AvambracciA4');
INSERT INTO sessione VALUES ('BicipitiB4');
INSERT INTO sessione VALUES ('Deltoidi C4');
INSERT INTO sessione VALUES ('TricipitiD4');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA5');
INSERT INTO sessione VALUES ('GluteiB5');
INSERT INTO sessione VALUES ('PolpacciC5');
INSERT INTO sessione VALUES ('Quadricipiti D5');
INSERT INTO sessione VALUES ('AvambracciA5');
INSERT INTO sessione VALUES ('BicipitiB5');
INSERT INTO sessione VALUES ('Deltoidi C5');
INSERT INTO sessione VALUES ('TricipitiD5');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA6');
INSERT INTO sessione VALUES ('GluteiB6');
INSERT INTO sessione VALUES ('PolpacciC6');
INSERT INTO sessione VALUES ('Quadricipiti D6');
INSERT INTO sessione VALUES ('AvambracciA6');
INSERT INTO sessione VALUES ('BicipitiB6');
INSERT INTO sessione VALUES ('Deltoidi C6');
INSERT INTO sessione VALUES ('TricipitiD6');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA7');
INSERT INTO sessione VALUES ('GluteiB7');
INSERT INTO sessione VALUES ('PolpacciC7');
INSERT INTO sessione VALUES ('Quadricipiti D7');
INSERT INTO sessione VALUES ('AvambracciA7');
INSERT INTO sessione VALUES ('BicipitiB7');
INSERT INTO sessione VALUES ('Deltoidi C7');
INSERT INTO sessione VALUES ('TricipitiD7');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA8');
INSERT INTO sessione VALUES ('GluteiB8');
INSERT INTO sessione VALUES ('PolpacciC8');
INSERT INTO sessione VALUES ('Quadricipiti D8');
INSERT INTO sessione VALUES ('AvambracciA8');
INSERT INTO sessione VALUES ('BicipitiB8');
INSERT INTO sessione VALUES ('Deltoidi C8');
INSERT INTO sessione VALUES ('TricipitiD8');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA9');
INSERT INTO sessione VALUES ('GluteiB9');
INSERT INTO sessione VALUES ('PolpacciC9');
INSERT INTO sessione VALUES ('Quadricipiti D9');
INSERT INTO sessione VALUES ('AvambracciA9');
INSERT INTO sessione VALUES ('BicipitiB9');
INSERT INTO sessione VALUES ('Deltoidi C9');
INSERT INTO sessione VALUES ('TricipitiD9');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA10');
INSERT INTO sessione VALUES ('GluteiB10');
INSERT INTO sessione VALUES ('PolpacciC10');
INSERT INTO sessione VALUES ('Quadricipiti D10');
INSERT INTO sessione VALUES ('AvambracciA10');
INSERT INTO sessione VALUES ('BicipitiB10');
INSERT INTO sessione VALUES ('Deltoidi C10');
INSERT INTO sessione VALUES ('TricipitiD10');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA11');
INSERT INTO sessione VALUES ('GluteiB11');
INSERT INTO sessione VALUES ('PolpacciC11');
INSERT INTO sessione VALUES ('Quadricipiti D11');
INSERT INTO sessione VALUES ('AvambracciA11');
INSERT INTO sessione VALUES ('BicipitiB11');
INSERT INTO sessione VALUES ('Deltoidi C11');
INSERT INTO sessione VALUES ('TricipitiD11');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA12');
INSERT INTO sessione VALUES ('GluteiB12');
INSERT INTO sessione VALUES ('PolpacciC12');
INSERT INTO sessione VALUES ('Quadricipiti D12');
INSERT INTO sessione VALUES ('AvambracciA12');
INSERT INTO sessione VALUES ('BicipitiB12');
INSERT INTO sessione VALUES ('Deltoidi C12');
INSERT INTO sessione VALUES ('TricipitiD12');
INSERT INTO sessione VALUES ('Bicipiti FemoraliA13');
INSERT INTO sessione VALUES ('GluteiB13');
INSERT INTO sessione VALUES ('PolpacciC13');
INSERT INTO sessione VALUES ('Quadricipiti D13');
INSERT INTO sessione VALUES ('AvambracciA13');
INSERT INTO sessione VALUES ('BicipitiB13');
INSERT INTO sessione VALUES ('Deltoidi C13');
INSERT INTO sessione VALUES ('TricipitiD13');
