-- MySQL Script generated by MySQL Workbench
-- 09/20/17 15:13:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Progetto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Progetto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Progetto` DEFAULT CHARACTER SET utf8 ;
USE `Progetto` ;

-- -----------------------------------------------------
-- Table `Progetto`.`Dipendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Dipendente` (
  `CodiceFiscale` VARCHAR(16) NOT NULL,
  `CodiceDocumento` VARCHAR(45) NOT NULL,
  `DataNascita` DATE NULL,
  `Prefettura` VARCHAR(45) NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Indirizzo` VARCHAR(255) NULL,
  PRIMARY KEY (`CodiceFiscale`),
  UNIQUE INDEX `Codice documento_UNIQUE` (`CodiceDocumento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Cliente` (
  `CodiceFiscale` VARCHAR(16) NOT NULL,
  `CodiceDocumento` VARCHAR(45) NOT NULL,
  `Prefettura` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Indirizzo` VARCHAR(255) NULL,
  `Altezza` VARCHAR(45) NULL,
  `DataNascita` DATE NULL,
  `TutorAttuale` VARCHAR(16) NULL,
  `Credibilita` INT NULL,
  `Stato` VARCHAR(45) NULL,
  `EntitaStato` VARCHAR(45) NULL,
  PRIMARY KEY (`CodiceFiscale`),
  UNIQUE INDEX `Codice documento_UNIQUE` (`CodiceDocumento` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  INDEX `fk_Cliente_Dipendente1_idx` (`TutorAttuale` ASC),
  CONSTRAINT `fk_Cliente_Dipendente1`
    FOREIGN KEY (`TutorAttuale`)
    REFERENCES `Progetto`.`Dipendente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Centro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Centro` (
  `Codice` INT NOT NULL,
  `Numero telefonico` INT NULL,
  `CapienzaMassimaClienti` INT NOT NULL,
  `Dimensione` INT NULL,
  `Indirizzo` VARCHAR(45) NOT NULL,
  `ClientiDentro` INT NOT NULL,
  PRIMARY KEY (`Codice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Responsabile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Responsabile` (
  `Responsabile` VARCHAR(16) NOT NULL,
  `Dipendente` VARCHAR(16) NOT NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`Responsabile`, `Dipendente`, `Centro`),
  INDEX `fk_Responsabile_Dipendente1_idx` (`Responsabile` ASC),
  INDEX `fk_Responsabile_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Responsabile_Dipendente`
    FOREIGN KEY (`Dipendente`)
    REFERENCES `Progetto`.`Dipendente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsabile_Dipendente1`
    FOREIGN KEY (`Responsabile`)
    REFERENCES `Progetto`.`Dipendente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsabile_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Scheda_allenamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Scheda_allenamento` (
  `Codice` INT NOT NULL,
  `Cliente` VARCHAR(16) NOT NULL,
  `Data inizio` DATE NOT NULL,
  `Data fine` DATE NULL,
  `Tutor` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Codice`),
  INDEX `fk_Scheda allenamento_Cliente1_idx` (`Cliente` ASC),
  INDEX `fk_Scheda allenamento_Dipendente1_idx` (`Tutor` ASC),
  CONSTRAINT `fk_Scheda allenamento_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Scheda allenamento_Dipendente1`
    FOREIGN KEY (`Tutor`)
    REFERENCES `Progetto`.`Dipendente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Sessione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Sessione` (
  `TipoSessione` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TipoSessione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Esercizio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Esercizio` (
  `Codice` INT NOT NULL,
  `DispendioEnergetico` INT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `NumeroRipetizioni` INT NULL,
  `NumeroPerRipetizione` INT NULL,
  `DurataRecupero` TIME(6) NULL,
  `DurataEsercizio` TIME(6) NULL,
  PRIMARY KEY (`Codice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Allenamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Allenamento` (
  `Esercizio` INT NOT NULL,
  `Sessione` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Esercizio`, `Sessione`),
  INDEX `fk_Allenamento_Sessione1_idx` (`Sessione` ASC),
  CONSTRAINT `fk_Proposta_Esercizio1`
    FOREIGN KEY (`Esercizio`)
    REFERENCES `Progetto`.`Esercizio` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Allenamento_Sessione1`
    FOREIGN KEY (`Sessione`)
    REFERENCES `Progetto`.`Sessione` (`TipoSessione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Sala` (
  `Nome` VARCHAR(45) NOT NULL,
  `Centro` INT NOT NULL,
  `Responsabile` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Nome`, `Centro`),
  INDEX `fk_Sala_Centro1_idx` (`Centro` ASC),
  INDEX `fk_Sala_Dipendente1_idx` (`Responsabile` ASC),
  CONSTRAINT `fk_Sala_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sala_Dipendente1`
    FOREIGN KEY (`Responsabile`)
    REFERENCES `Progetto`.`Dipendente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Macchinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Macchinario` (
  `Codice` INT NOT NULL,
  `Tipologia` VARCHAR(45) NULL,
  `ConsumoEnergetico` INT NULL,
  `PercentualeUsura` INT NOT NULL,
  `Sala` VARCHAR(45) NOT NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`Codice`),
  INDEX `fk_Attrezzatura_Sala1_idx` (`Sala` ASC, `Centro` ASC),
  CONSTRAINT `fk_Attrezzatura_Sala1`
    FOREIGN KEY (`Sala` , `Centro`)
    REFERENCES `Progetto`.`Sala` (`Nome` , `Centro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Attrezzatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Attrezzatura` (
  `Esercizio` INT NOT NULL,
  `Configurazione` VARCHAR(45) NOT NULL,
  `TipologiaMacchinario` VARCHAR(45) NOT NULL,
  INDEX `fk_Supporto_Esercizio1_idx` (`Esercizio` ASC),
  PRIMARY KEY (`Esercizio`, `TipologiaMacchinario`),
  CONSTRAINT `fk_Supporto_Esercizio1`
    FOREIGN KEY (`Esercizio`)
    REFERENCES `Progetto`.`Esercizio` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Turno` (
  `GiornoSettimana` INT NOT NULL,
  `Orario inizio` TIME(4) NOT NULL,
  `Dipendente` VARCHAR(16) NOT NULL,
  `Centro` INT NOT NULL,
  `OrarioFine` TIME(4) NULL,
  `Attivita` VARCHAR(45) NULL,
  PRIMARY KEY (`GiornoSettimana`, `Orario inizio`, `Dipendente`, `Centro`),
  INDEX `fk_Turno_Dipendente1_idx` (`Dipendente` ASC),
  INDEX `fk_Turno_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Turno_Dipendente1`
    FOREIGN KEY (`Dipendente`)
    REFERENCES `Progetto`.`Dipendente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Corso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Corso` (
  `Codice` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Livello` VARCHAR(45) NULL,
  `Data fine` DATE NULL,
  `Data inizio` DATE NOT NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`Codice`),
  INDEX `fk_Corso_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Corso_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Iscrizione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Iscrizione` (
  `Corso` INT NOT NULL,
  `Cliente` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Corso`, `Cliente`),
  INDEX `fk_Iscrizione_Cliente1_idx` (`Cliente` ASC),
  CONSTRAINT `fk_Iscrizione_Corso1`
    FOREIGN KEY (`Corso`)
    REFERENCES `Progetto`.`Corso` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Iscrizione_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Calendario_corso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Calendario_corso` (
  `Giorno Settimana` INT NOT NULL,
  `Orario_inizio` TIME(4) NOT NULL,
  `Corso` INT NOT NULL,
  `Durata` TIME(4) NULL,
  `Sala` VARCHAR(45) NOT NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`Giorno Settimana`, `Orario_inizio`, `Corso`, `Sala`, `Centro`),
  INDEX `fk_Calendario Corso_Corso1_idx` (`Corso` ASC),
  INDEX `fk_Calendario corso_Sala1_idx` (`Sala` ASC, `Centro` ASC),
  CONSTRAINT `fk_Calendario Corso_Corso1`
    FOREIGN KEY (`Corso`)
    REFERENCES `Progetto`.`Corso` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendario corso_Sala1`
    FOREIGN KEY (`Sala` , `Centro`)
    REFERENCES `Progetto`.`Sala` (`Nome` , `Centro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Calendario_centro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Calendario_centro` (
  `Giorno settimana` INT NOT NULL,
  `OrarioApertura` VARCHAR(45) NOT NULL,
  `Centro` INT NOT NULL,
  `OrarioChiusura` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Giorno settimana`, `OrarioApertura`, `Centro`),
  INDEX `fk_Turno_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Turno_Centro10`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Misurazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Misurazione` (
  `Data` DATE NOT NULL,
  `Medico` VARCHAR(16) NOT NULL,
  `Cliente` VARCHAR(16) NOT NULL,
  `Peso` INT NULL,
  `PercentualeGrassa` INT NULL,
  `PercentualeMagra` INT NULL,
  `PercentualeAcqua` INT NULL,
  PRIMARY KEY (`Data`, `Medico`, `Cliente`),
  INDEX `fk_Cliente_Dipendente1_idx` (`Medico` ASC),
  INDEX `fk_Misurazione_Cliente1_idx` (`Cliente` ASC),
  CONSTRAINT `fk_Cliente_Dipendente10`
    FOREIGN KEY (`Medico`)
    REFERENCES `Progetto`.`Dipendente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Misurazione_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Scheda_alimentazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Scheda_alimentazione` (
  `Codice` INT NOT NULL,
  `Nutrizionista` VARCHAR(16) NOT NULL,
  `Cliente` VARCHAR(16) NOT NULL,
  `DataInizio` DATE NOT NULL,
  `DataFine` DATE NULL,
  `IntervalloVisiteProgrammato` INT NULL,
  PRIMARY KEY (`Codice`),
  INDEX `fk_Scheda Alimentazione_Dipendente1_idx` (`Nutrizionista` ASC),
  INDEX `fk_Scheda Alimentazione_Cliente1_idx` (`Cliente` ASC),
  CONSTRAINT `fk_Scheda Alimentazione_Dipendente1`
    FOREIGN KEY (`Nutrizionista`)
    REFERENCES `Progetto`.`Dipendente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Scheda Alimentazione_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Dieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Dieta` (
  `Codice` INT NOT NULL,
  `Calorie massime` INT NULL,
  `Calorie minime` INT NULL,
  `NumeroPasti` INT NULL,
  `ComposizionePasti` VARCHAR(500) NULL,
  `SchedaAlimentazione` INT NOT NULL,
  PRIMARY KEY (`Codice`),
  INDEX `fk_Dieta_Scheda Alimentazione1_idx` (`SchedaAlimentazione` ASC),
  CONSTRAINT `fk_Dieta_Scheda Alimentazione1`
    FOREIGN KEY (`SchedaAlimentazione`)
    REFERENCES `Progetto`.`Scheda_alimentazione` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Obiettivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Obiettivo` (
  `Scopo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Scopo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Fine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Fine` (
  `Obiettivo` varchar(70) NOT NULL,
  `SchedaAlimentazione` INT NOT NULL,
  PRIMARY KEY (`Obiettivo`, `SchedaAlimentazione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Potenziamento_muscolare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Potenziamento_muscolare` (
  `Obiettivo` VARCHAR(45) NOT NULL,
  `GruppoMuscolare` VARCHAR(45) NOT NULL,
  `Livello` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Obiettivo`, `GruppoMuscolare`, `Livello`),
  CONSTRAINT `fk_Gruppo muscolare_Obiettivo1`
    FOREIGN KEY (`Obiettivo`)
    REFERENCES `Progetto`.`Obiettivo` (`Scopo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Contratto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Contratto` (
  `Codice` INT NOT NULL,
  `Cliente` VARCHAR(16) NOT NULL,
  `Consulente` VARCHAR(16) NOT NULL,
  `Prezzo` INT NOT NULL,
  `DataSottoscrizione` DATE NOT NULL,
  `AccessiSettimanali` VARCHAR(45) NULL,
  `Durata` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Saldato` TINYINT(1) NULL,
  PRIMARY KEY (`Codice`),
  INDEX `fk_Contratto_Cliente1_idx` (`Cliente` ASC),
  INDEX `fk_Contratto_Dipendente1_idx` (`Consulente` ASC),
  CONSTRAINT `fk_Contratto_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contratto_Dipendente1`
    FOREIGN KEY (`Consulente`)
    REFERENCES `Progetto`.`Dipendente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Sede` (
  `Contratto` INT NOT NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`Contratto`, `Centro`),
  INDEX `fk_Sede_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Sede_Contratto1`
    FOREIGN KEY (`Contratto`)
    REFERENCES `Progetto`.`Contratto` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sede_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Possibilita_accesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Possibilita_accesso` (
  `Contratto` INT NOT NULL,
  `Sala` VARCHAR(45) NOT NULL,
  `Centro` INT NOT NULL,
  `AccessiSettimanali` INT NULL,
  PRIMARY KEY (`Contratto`, `Sala`, `Centro`),
  INDEX `fk_Possibilita Accesso_Sala1_idx` (`Sala` ASC, `Centro` ASC),
  CONSTRAINT `fk_Possibilita Accesso_Contratto1`
    FOREIGN KEY (`Contratto`)
    REFERENCES `Progetto`.`Contratto` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Possibilita Accesso_Sala1`
    FOREIGN KEY (`Sala` , `Centro`)
    REFERENCES `Progetto`.`Sala` (`Nome` , `Centro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Pagamento_rateizzato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Pagamento_rateizzato` (
  `Contratto` INT NOT NULL,
  `Istituto` VARCHAR(100) NULL,
  `Interesse` INT NULL,
  PRIMARY KEY (`Contratto`),
  CONSTRAINT `fk_Pagamento_Contratto1`
    FOREIGN KEY (`Contratto`)
    REFERENCES `Progetto`.`Contratto` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Rata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Rata` (
  `Scadenza` DATE NOT NULL,
  `Pagamento` INT NOT NULL,
  `Stato` VARCHAR(45) NOT NULL,
  `Importo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Scadenza`, `Pagamento`),
  INDEX `fk_Rata_Pagamento1_idx` (`Pagamento` ASC),
  CONSTRAINT `fk_Rata_Pagamento1`
    FOREIGN KEY (`Pagamento`)
    REFERENCES `Progetto`.`Pagamento_rateizzato` (`Contratto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Scelta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Scelta` (
  `Obiettivo` VARCHAR(45) NOT NULL,
  `Contratto` INT NOT NULL,
  PRIMARY KEY (`Obiettivo`, `Contratto`),
  INDEX `fk_Scelta_Contratto1_idx` (`Contratto` ASC),
  CONSTRAINT `fk_Scelta_Obiettivo1`
    FOREIGN KEY (`Obiettivo`)
    REFERENCES `Progetto`.`Obiettivo` (`Scopo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Scelta_Contratto1`
    FOREIGN KEY (`Contratto`)
    REFERENCES `Progetto`.`Contratto` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Accesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Accesso` (
  `MomentoEntrata` TIMESTAMP NOT NULL,
  `Cliente` VARCHAR(16) NOT NULL,
  `Centro` INT NOT NULL,
  `MometoUscita` TINYINT(1) NOT NULL,
  PRIMARY KEY (`MomentoEntrata`, `Cliente`),
  INDEX `fk_Accesso_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Accesso_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accesso_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Spogliatoio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Spogliatoio` (
  `Identificatore` INT NOT NULL,
  `Posizione` VARCHAR(45) NOT NULL,
  `Capienza` VARCHAR(45) NOT NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`Identificatore`),
  INDEX `fk_Spogliatoio_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Spogliatoio_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Armadietto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Armadietto` (
  `CodiceIdentificativo` INT NOT NULL,
  `Spogliatoio` INT NOT NULL,
  `Occupato` TINYINT(1) NOT NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`CodiceIdentificativo`, `Spogliatoio`),
  INDEX `fk_Armadietto_Spogliatoio1_idx` (`Spogliatoio` ASC),
  INDEX `fk_Armadietto_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Armadietto_Spogliatoio1`
    FOREIGN KEY (`Spogliatoio`)
    REFERENCES `Progetto`.`Spogliatoio` (`Identificatore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Armadietto_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Assegnamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Assegnamento` (
  `Armadietto` INT NOT NULL,
  `Momento` TIMESTAMP NOT NULL,
  `CodiceSblocco` INT NOT NULL,
  `Cliente` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Armadietto`, `Momento`),
  INDEX `fk_Assegnamento_Accesso1_idx` (`Cliente` ASC, `Momento` ASC),
  CONSTRAINT `fk_Assegnamento_Armadietto1`
    FOREIGN KEY (`Armadietto`)
    REFERENCES `Progetto`.`Armadietto` (`CodiceIdentificativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Assegnamento_Accesso1`
    FOREIGN KEY (`Cliente` , `Momento`)
    REFERENCES `Progetto`.`Accesso` (`Cliente` , `MomentoEntrata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Ordine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Ordine` (
  `CodiceInterno` INT NOT NULL,
  `CodiceEsterno` INT NOT NULL,
  `DataEffettuazione` DATE NOT NULL,
  `DataConsegnaPreferita` DATE NULL,
  `DataConsegna` DATE NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`CodiceInterno`),
  INDEX `fk_Ordine_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Ordine_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Fornitore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Fornitore` (
  `Partita IVA` DOUBLE NOT NULL,
  `Indirizzo` VARCHAR(100) NOT NULL,
  `NomeCommerciale` VARCHAR(45) NOT NULL,
  `FirmaSocietaria` VARCHAR(15) NOT NULL,
  `NumeroTelefonico` INT NOT NULL,
  PRIMARY KEY (`Partita IVA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Integratore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Integratore` (
  `Codice` INT NOT NULL,
  `Nome commerciale` VARCHAR(45) NOT NULL,
  `SostanzaContenuta` VARCHAR(45) NOT NULL,
  `PezziPerConfezione` INT NULL,
  `QuantiaProdotto` INT NULL,
  `Scadenza` DATE NOT NULL,
  `Fornitore` DOUBLE NOT NULL,
  PRIMARY KEY (`Codice`),
  INDEX `fk_Integratore_Fornitore1_idx` (`Fornitore` ASC),
  CONSTRAINT `fk_Integratore_Fornitore1`
    FOREIGN KEY (`Fornitore`)
    REFERENCES `Progetto`.`Fornitore` (`Partita IVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Magazzino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Magazzino` (
  `Integratore` INT NOT NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`Integratore`, `Centro`),
  INDEX `fk_Magazzino_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Magazzino_Integratore1`
    FOREIGN KEY (`Integratore`)
    REFERENCES `Progetto`.`Integratore` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Magazzino_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Acquisto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Acquisto` (
  `Cliente` VARCHAR(16) NOT NULL,
  `Integratore` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Centro` INT NOT NULL,
  PRIMARY KEY (`Cliente`, `Integratore`),
  INDEX `fk_Acquisto_Integratore1_idx` (`Integratore` ASC),
  INDEX `fk_Acquisto_Cliente1_idx` (`Cliente` ASC),
  INDEX `fk_Acquisto_Centro1_idx` (`Centro` ASC),
  CONSTRAINT `fk_Acquisto_Integratore1`
    FOREIGN KEY (`Integratore`)
    REFERENCES `Progetto`.`Integratore` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acquisto_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acquisto_Centro1`
    FOREIGN KEY (`Centro`)
    REFERENCES `Progetto`.`Centro` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Progetto`.`Prodotto_ordinato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Prodotto_ordinato` (
  `Integratore` INT NOT NULL,
  `CodiceOrdine` INT NOT NULL,
  PRIMARY KEY (`Integratore`, `CodiceOrdine`),
  INDEX `fk_Prodotto Ordinato_Ordine1_idx` (`CodiceOrdine` ASC),
  CONSTRAINT `fk_Prodotto Ordinato_Integratore1`
    FOREIGN KEY (`Integratore`)
    REFERENCES `Progetto`.`Integratore` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prodotto Ordinato_Ordine1`
    FOREIGN KEY (`CodiceOrdine`)
    REFERENCES `Progetto`.`Ordine` (`CodiceInterno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Amicizia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Amicizia` (
  `Richiedente` VARCHAR(16) NOT NULL,
  `Ricevente` VARCHAR(16) NOT NULL,
  `Stato` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Richiedente`, `Ricevente`),
  INDEX `fk_Amicizia_Cliente2_idx` (`Ricevente` ASC),
  CONSTRAINT `fk_Amicizia_Cliente1`
    FOREIGN KEY (`Richiedente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Amicizia_Cliente2`
    FOREIGN KEY (`Ricevente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Sfida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Sfida` (
  `Codice` INT NOT NULL,
  `Data lancio` DATE NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Proponente` VARCHAR(16) NOT NULL,
  `SchedaAllenamentoAssociata` INT NOT NULL,
  `Scopo` VARCHAR(500) NULL,
  `SchedaAlimentazioneAssociata` INT NULL,
  `Data inizio` DATE NULL,
  `Scadenza` DATE NULL,
  INDEX `fk_Sfida_Scheda Allenamento1_idx` (`SchedaAllenamentoAssociata` ASC),
  PRIMARY KEY (`Codice`),
  INDEX `fk_Sfida_Scheda Alimentazione1_idx` (`SchedaAlimentazioneAssociata` ASC),
  CONSTRAINT `fk_Sfida_Cliente1`
    FOREIGN KEY (`Proponente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sfida_Scheda Allenamento1`
    FOREIGN KEY (`SchedaAllenamentoAssociata`)
    REFERENCES `Progetto`.`Scheda_allenamento` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sfida_Scheda Alimentazione1`
    FOREIGN KEY (`SchedaAlimentazioneAssociata`)
    REFERENCES `Progetto`.`Scheda_alimentazione` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Partecipante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Partecipante` (
  `Partecipante` VARCHAR(16) NOT NULL,
  `Sfida` INT NOT NULL,
  `Avanzamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Partecipante`, `Sfida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Post` (
  `Codice` INT NOT NULL,
  `Pubblicatore` VARCHAR(16) NOT NULL,
  `Timestamp` TIMESTAMP NULL,
  `Testo` VARCHAR(500) NULL,
  PRIMARY KEY (`Codice`),
  INDEX `fk_Post_Cliente1_idx` (`Pubblicatore` ASC),
  CONSTRAINT `fk_Post_Cliente1`
    FOREIGN KEY (`Pubblicatore`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Thread`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Thread` (
  `Sfida` VARCHAR(45) NOT NULL,
  `Post` INT NOT NULL,
  PRIMARY KEY (`Sfida`, `Post`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Risposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Risposta` (
  `Post` INT NOT NULL,
  `Rsiposta` INT NOT NULL,
  PRIMARY KEY (`Post`, `Rsiposta`),
  INDEX `fk_Risposta_Post2_idx` (`Rsiposta` ASC),
  CONSTRAINT `fk_Risposta_Post1`
    FOREIGN KEY (`Post`)
    REFERENCES `Progetto`.`Post` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Risposta_Post2`
    FOREIGN KEY (`Rsiposta`)
    REFERENCES `Progetto`.`Post` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Giudizio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Giudizio` (
  `Post` INT NOT NULL,
  `Cliente` VARCHAR(16) NOT NULL,
  `Valore` INT NOT NULL,
  `Timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`Post`, `Cliente`),
  INDEX `fk_Giudizio_Cliente1_idx` (`Cliente` ASC),
  CONSTRAINT `fk_Giudizio_Post1`
    FOREIGN KEY (`Post`)
    REFERENCES `Progetto`.`Post` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Giudizio_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Attivita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Attivita` (
  `Nome` VARCHAR(100) NOT NULL,
  `Interessato` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Nome`, `Interessato`),
  INDEX `fk_Attivita_Cliente1_idx` (`Interessato` ASC),
  CONSTRAINT `fk_Attivita_Cliente1`
    FOREIGN KEY (`Interessato`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Allegato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Allegato` (
  `LinkEsterno` VARCHAR(500) NOT NULL,
  `Post` INT NOT NULL,
  PRIMARY KEY (`LinkEsterno`, `Post`),
  INDEX `fk_Allegato_Post1_idx` (`Post` ASC),
  CONSTRAINT `fk_Allegato_Post1`
    FOREIGN KEY (`Post`)
    REFERENCES `Progetto`.`Post` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Esercizio_svolto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Esercizio_svolto` (
  `Inizio` TIMESTAMP NOT NULL,
  `Esercizio` INT NOT NULL,
  `Cliente` VARCHAR(16) NOT NULL,
  `CalorieConsumate` INT NULL,
  `BattitoCardiacoMedio` INT NULL,
  `TempoImpiegato` TIME(6) NULL,
  `TempoRecuperoMedio` TIME(6) NULL,
  `Configurazione` VARCHAR(45) NULL,
  `Atrezzatura` INT NULL,
  PRIMARY KEY (`Inizio`, `Esercizio`, `Cliente`),
  INDEX `fk_Esercizio svolto_Esercizio1_idx` (`Esercizio` ASC),
  INDEX `fk_Esercizio svolto_Cliente1_idx` (`Cliente` ASC),
  INDEX `fk_Esercizio svolto_Attrezzatura1_idx` (`Atrezzatura` ASC),
  CONSTRAINT `fk_Esercizio svolto_Esercizio1`
    FOREIGN KEY (`Esercizio`)
    REFERENCES `Progetto`.`Esercizio` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Esercizio svolto_Cliente1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Esercizio svolto_Attrezzatura1`
    FOREIGN KEY (`Atrezzatura`)
    REFERENCES `Progetto`.`Macchinario` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Cerchia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Cerchia` (
  `Nome cerchia` VARCHAR(100) NOT NULL,
  `Richiedente` VARCHAR(16) NOT NULL,
  `Ricevente` VARCHAR(16) NOT NULL,
  `DirezioneInserimento` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Nome cerchia`, `Richiedente`, `Ricevente`, `DirezioneInserimento`),
  INDEX `fk_Cerchia Ricevente_Amicizia1_idx` (`Richiedente` ASC, `Ricevente` ASC),
  CONSTRAINT `fk_Cerchia Ricevente_Amicizia1`
    FOREIGN KEY (`Richiedente` , `Ricevente`)
    REFERENCES `Progetto`.`Amicizia` (`Richiedente` , `Ricevente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Suddivisione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Suddivisione` (
  `Sessione` VARCHAR(45) NOT NULL,
  `SchedaAllenamento` INT NOT NULL,
  `GiornoSettimana` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sessione`, `SchedaAllenamento`, `GiornoSettimana`),
  INDEX `fk_Suddivisione_Scheda Allenamento1_idx` (`SchedaAllenamento` ASC),
  CONSTRAINT `fk_Suddivisione_Sessione1`
    FOREIGN KEY (`Sessione`)
    REFERENCES `Progetto`.`Sessione` (`TipoSessione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suddivisione_Scheda Allenamento1`
    FOREIGN KEY (`SchedaAllenamento`)
    REFERENCES `Progetto`.`Scheda_allenamento` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Progetto`.`Post recente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Progetto`.`Post recente` (
  `Codice` INT NOT NULL,
  `Pubblicatore` VARCHAR(16) NOT NULL,
  `Timestamp` TIMESTAMP NULL,
  `Testo` VARCHAR(500) NULL,
  PRIMARY KEY (`Codice`),
  INDEX `fk_Post_Cliente1_idx` (`Pubblicatore` ASC),
  CONSTRAINT `fk_Post_Cliente10`
    FOREIGN KEY (`Pubblicatore`)
    REFERENCES `Progetto`.`Cliente` (`CodiceFiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
